FROM node as build

WORKDIR /app/frontend
COPY package.json .
RUN npm install
COPY . .

ENV REACT_APP_API_URL=http://127.0.0.1:8081/api/v1/quote/random
ENV NODE_ENV=production
RUN npm run build

FROM nginx
COPY --from=build /app/frontend/build /usr/share/nginx/html
